### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by marcqualie** [wallaby-rails/wallaby-rails#110]
I started using this then realised when creating templates it's using Bootstrap 3 and FontAwesome 4.

Are you open to upgrading these as they've been GA for >6 months now?

**Comment by tian-im** [comment]
It depends on how many js libraries used in Wallaby have moved to Bootstrap 4.

However, it is possible to develop a theme (layout/template) of Bootstrap 4 on top of Wallaby. I can write up a document how to do that and hopefully someone can pick it up before I do.

Otherwise, I'm interested in upgrading it to Bootstrap 4 later, just I can't promise a timeline for this :) Since I have other high priority features (in [CHANGELOG.md](https://github.com/reinteractive/wallaby/blob/master/CHANGELOG.md)) wanting to push out.

Please let me if you have other feedbacks. If you think the documentation is not clear, please let me know or help to improve it.

Cheers

**Comment by tian-im** [comment]
Bootstrap 4 is in
