### ISSUE TITLE
How to improve index rendering performance?

### ISSUE THREAD

**Issue by pustomytnyk** [wallaby-rails/wallaby-rails#132]
Rendering the index is quite slow (up to few seconds) because each makes separate `render` call. Maybe we could rewrite it to have some kind of rendering classes that can optionally render a partial?
```ruby
class IndexRenderer
  def integer(some_value)
    some_value.to_s
  end

  def some_complex_type(some_value)
    view.render 'some_complex_type', value: some_value
  end
end
```

**Comment by tian-im** [comment]
yeah, have to admit that performance in development is really bad, since it's taking advantage of rails partials which is doing runtime partial lookup and erb compilation. i've done a couple of attempts before, but didn't come up with any good solution to improve the performance.

i think `IndexRenderer` is a good idea, just i need to think about a good way that it can be configured and inherited from.

thanks @pustomytnyk for this suggestion, will start working on it when 5.2.0 is out!

**Comment by tian-im** [comment]
close it now as PR gets merged
