### ISSUE TITLE
Gem dependencies

### ISSUE THREAD

**Issue by pustomytnyk** [wallaby-rails/wallaby-rails#157]
I was able to initialize it on Rails 6 with next gems:

```ruby
gem 'wallaby', github: 'wallaby-rails/wallaby'
gem 'wallaby-core', github: 'wallaby-rails/wallaby-core'
gem 'wallaby-active_record', github: 'wallaby-rails/wallaby-active_record'
gem 'kaminari'
gem 'wallaby-her', github: 'wallaby-rails/wallaby-her'
gem 'codemirror-rails', github: 'fixlr/codemirror-rails', branch: 'updates'
```
Shouldn't kaminari be added as dependency to gemspec? Also it currently requires wallaby-her.

**Comment by tian-im** [comment]
Hi @pustomytnyk,

Sorry for the late reply.

Regarding the `kaminari`, it's not required, as pagination can live without it.
About `wallaby-her`, I'm going to remove this dependency as I'm working on supporting Rails 6. I think the change will roughly take around 1 month to finalize. Hopefully, that's not going to stop you from upgrading to Rails 6.

Cheers,

Tian

**Comment by tian-im** [comment]
Hi @pustomytnyk ,

I've made the following dependency changes:

- `kaminari` is required by `wallaby-active_record` instead of `wallaby`. See https://github.com/wallaby-rails/wallaby-active_record/blob/master/wallaby-active_record.gemspec
- `wallaby-her` is no longer required by `wallaby`. See https://github.com/wallaby-rails/wallaby/blob/master/wallaby.gemspec

PS: wallaby 6.0.0 is released, please give it a go and let me know how'd you go.

Will close this issue now.
