### ISSUE TITLE
Default theme isn't used

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#168]
Wallaby appears to be using the layout defined in the main `::ApplicationController` by default. I had to add this to our wallaby `ApplicationController` to get it to use the default theme.

```
self.theme_name = "wallaby/resources"
```

Shouldn't this theme be used by default and override the layout defined in `::ApplicationController`? It might also be nice to add information on the default them to the [themes docs](https://github.com/wallaby-rails/wallaby/blob/master/docs/theme.md).

**Comment by tian-im** [comment]
Didn't realize that `::ApplicationController` has defined its own layout and this impacts `Wallaby::ResourcesController`. I'm going to set layout to `wallaby/resources` manually so that it's not going to be impacted.

BTW, the `Wallaby::ApplicationController` and `Wallaby::SecureController` will be gone in the new release, because I want to move the code into a concern `Wallaby::ResourcesConcern` instead. So that in the future, other controllers can just include `Wallaby::ResourcesConcern` and gets the same functionalities as Wallaby.

**Comment by ryanb** [comment]
Nice, that would remove the need for the base controller config.

**Comment by tian-im** [comment]
yep, it's in the master now

**Comment by tian-im** [comment]
You can try to use the GitHub link for `wallaby-core`:

```ruby
gem 'wallaby-core', git: 'https://github.com/wallaby-rails/wallaby-core.git'
```

and point to the `master` branch for now until I get a stable release version if it's ok.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.1 and see if it works for you?

**Comment by ryanb** [comment]
This is working, thanks! Closing.
