### ISSUE TITLE
Error: primary::SchemaMigration is not a valid Class name.

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#186]
I see this error in the log when running Wallaby 6.1.2:

```
WALLABY ERROR: `primary::SchemaMigration` is not a valid Class name.
```

Is it trying to find a model class for every table? Rails manages this table I think.

**Comment by tian-im** [comment]
Yeah, I saw this error as well. It should be a fake class that comes from Rails test, but I'm not sure how it gets into the environment.

The reason it shows up is that Wallaby will go through every ActiveRecord class and associate it with a mode so that Wallaby knows how to handle it when building the Wallaby::Map.

But yeah, I think it's safe to ignore it until Rails team fixes it.

**Comment by ryanb** [comment]
Is there an active issue for this on the Rails repo? The closest thing I could find is this issue: https://github.com/rails/rails/issues/36757

However this doesn't look like something they plan to fix. Can you add an exception in Wallaby to ignore that class name?

**Comment by tian-im** [comment]
Sure thing

**Comment by tian-im** [comment]
@ryanb could you update to wallaby 6.1.3 and see if it is ok for you?

**Comment by ryanb** [comment]
Fixed, thanks!
